### ISSUE TITLE
Bug in indexing dev set examples UD POS

### ISSUE THREAD

**Issue by blazejdolicki** [google-research/xtreme#25]
Something is wrong with indexing examples in the dev set of the POS tagging task. In this file every index is assigned to one sentence. However, we can see that index 772 is assigned to two sentences
![image](https://user-images.githubusercontent.com/29718307/81682513-2ad5b100-9455-11ea-9cc6-3bc6f0e83203.png)

This results in predictions of two separate sentences being merged together, like in the following table, which ruins the alignment between sentence and its prediction. You can see that the higlighted ending in row 772 should actually be in the next row.
![image](https://user-images.githubusercontent.com/29718307/81682846-8c961b00-9455-11ea-9bbb-bde7bbf9989c.png)

Row 772 is an example, but there are two more such erroneous rows.

**Comment by JunjieHu** [comment]
@blazejdolicki The *.idx files actually record the original sentence index in the `download/udpos/dev-xx.tsv` files. The reason to create this index file is that most pre-trained models have their own tokenizers which tokenize an original sentence to a longer one. The length of the tokenized sentences might exceed a pre-defined value such as 128, 256, or 512. 

Current models can only make tag predictions for sequences with a maximum length such as 512. In our paper, we used 128 as the maximum length. So to make tag predictions for a longer tokenized sentence, we break it into two for separate predictions, and record their original index in order to merge the two predicted tag sequences as the final output. 

In your above example, you can check Line 13067 of the original file in `download/udpos/dev-nl.tsv` to see that the two tokenized sentences with the same index actually come from one sentence. 

Let me know if the above explanation is clean to you.

**Comment by blazejdolicki** [comment]
Thank you for clarification! So I used the file `download/udpos/udpos_processed_maxlen128/nl/dev.xlm-roberta-large` (where the sentences exceeding the limit are split) instead of `download/udpos/dev-nl.tsv` and that caused to the problem. After changing the file, the alignment is correct. I'm closing the issue.
