### ISSUE TITLE
Test sets in downloaded UD POS don't have labels

### ISSUE THREAD

**Issue by blazejdolicki** [google-research/xtreme#29]
Description pretty much says it all, the test labels are not downloaded which makes evaluation on test set impossible. Is there a valid reason for that or it's just an oversight? I checked the  [original link](https://lindat.mff.cuni.cz/repository/xmlui/bitstream/handle/11234/1-3105/ud-treebanks-v2.5.tgz) and the test labels are available in the .conllu files.

**Comment by sebastianruder** [comment]
Hi Błażej, please see the note [here](https://github.com/google-research/xtreme#download-the-data). In particular, in order to prevent hill-climbing and accidental evaluation we remove test labels during pre-processing. We ask people not to evaluate on the test sets themselves and only to submit their predictions to the public leaderboard, which will be available [here](https://sites.research.google/xtreme) soon.

**Comment by blazejdolicki** [comment]
Thanks for such a swift response! I overlooked it.
