### ISSUE TITLE
Bug in tydiqa training/evaluation file?

### ISSUE THREAD

**Issue by ffaisal93** [google-research/xtreme#66]
Hello,
When I try to train zero-shot (train on english data, test on the others) tydiqa-goldp following the script and command (bash scripts/train.sh tydiqa) it gives 0  on all evaluation datasets. I think there is definately a bug but couldn't find it. I did not change anything except in run_qa.sh it will be:
TRAIN_FILE=${TASK_DATA_DIR}/tydiqa-goldp-v1.1-train/tydiqa.goldp.en.train.json
instead of
TRAIN_FILE=${TASK_DATA_DIR}/tydiqa-goldp-v1.1-train/tydiqa.en.train.json

Here is my training log: https://paste.ee/p/e6sgs

Kindly let me know if I am missing something here

**Comment by sebastianruder** [comment]
Hi @ffaisal93, thanks for highlighting this. Please note that in order to prevent accidental cheating, we [remove the answers](https://github.com/google-research/xtreme/blob/master/utils_preprocess.py#L462) in the test data when downloading the datasets. This is likely the reason that you see test scores of 0 when evaluating on TyDiQA.

**Comment by ffaisal93** [comment]
@sebastianruder , Thank you for the reply. That would be the reason.
